### ISSUE TITLE
Build Failed. Please write a Github CI/CD Actions pr give your binary

### ISSUE THREAD

**Issue by rihaq** [vsevolod-mineev/simplex-aarch64-termux#1]
Failed to build basement-0.0.12.
Build log (
/root/.cabal/logs/ghc-8.10.7/basement-0.0.12-823676f5497255fe977c6add9d889b061d3b8a78e2814386d0d6a73af2c5434d.log
):
Configuring library for basement-0.0.12..
Preprocessing library for basement-0.0.12..
linking dist/build/Basement/Terminal/Size_hsc_make.o failed (exit code 1)
rsp file was: "dist/build/Basement/Terminal/hsc2hscall8836-2.rsp"
command was: /data/data/com.termux/files/usr/bin/gcc dist/build/Basement/Terminal/Size_hsc_make.o dist/build/Basement/Terminal/Size_hsc_utils.o -o dist/build/Basement/Terminal/Size_hsc_make -fuse-ld=lld -Wl,-z,noexecstack -fuse-ld=lld -Wl,-z,noexecstack -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/base-4.14.3.0 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/base-4.14.3.0 -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/integer-gmp-1.0.3.0 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/integer-gmp-1.0.3.0 -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/ghc-prim-0.6.1 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/ghc-prim-0.6.1 -lc -lm -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/rts -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/rts -lm -lrt -ldl -lnuma -lpthread
error: ld.lld: error: unable to find library -lnuma
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

Failed to build clock-0.8.3.
Build log (
/root/.cabal/logs/ghc-8.10.7/clock-0.8.3-f412911ac0292b6b3fe4052b0f7dd596a1aea615edfdf66a8643e9b15c0fb1d3.log
):
Configuring library for clock-0.8.3..
Preprocessing library for clock-0.8.3..
linking dist/build/System/Clock_hsc_make.o failed (exit code 1)
rsp file was: "dist/build/System/hsc2hscall8710-2.rsp"
command was: /data/data/com.termux/files/usr/bin/gcc dist/build/System/Clock_hsc_make.o dist/build/System/Clock_hsc_utils.o -o dist/build/System/Clock_hsc_make -fuse-ld=lld -Wl,-z,noexecstack -fuse-ld=lld -Wl,-z,noexecstack -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/base-4.14.3.0 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/base-4.14.3.0 -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/integer-gmp-1.0.3.0 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/integer-gmp-1.0.3.0 -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/ghc-prim-0.6.1 -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/ghc-prim-0.6.1 -lc -lm -L/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/rts -Wl,-R,/root/.ghcup/ghc/8.10.7/lib/ghc-8.10.7/rts -lm -lrt -ldl -lnuma -lpthread
error: ld.lld: error: unable to find library -lnuma
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

cabal: Failed to build basement-0.0.12 (which is required by exe:simplex-chat
from simplex-chat-1.1.0). See the build log above for details.
Failed to build clock-0.8.3 (which is required by exe:simplex-chat from
simplex-chat-1.1.0). See the build log above for details.
Failed to build entropy-0.4.1.7 (which is required by exe:simplex-chat from
simplex-chat-1.1.0). The failure occurred during the configure step. The
exception was:
dieVerbatim: user error (cabal: '/root/.ghcup/bin/ghc' exited with an error:
You are using an unsupported version of LLVM!
Currently only 9 to 13 is supported. System LLVM version: 13.0.0
We will try though...
ld.lld: error: unable to find library -lnuma
clang-13: error: linker command failed with exit code 1 (use -v to see
invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

**Comment by vsevolod-mineev** [comment]
The CI/CD is implemented for SImpleX Chat here: https://github.com/simplex-chat/simplex-chat

This is a garage project to have this work on proot-distro from Termux.

I have compiled the latest version 1.1.1 and uploaded it for you here: https://github.com/vsevolod-mineev/simplex-aarch64-termux/releases/tag/v1.1.1

Kindest regards,
VM
